blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('test', views.post_kosong, name= 'post_kosong'),
    path('', views.home, name ='index'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),


]

tutorial_djangogirl/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexView, name='index'),
    path('article/', views.article_list, name='article_list'),
    path('article/new', views.article_new, name='article_new'),
    path('article/<pk>/edit', views.article_edit, name='article_edit'),
    path('article/<pk>/publish', views.article_publish, name='article_publish'),
    path('article/<pk>/delete', views.article_delete, name='article_delete'),
    path('article/<slug>', views.article_detail, name='article_detail'),
]

tutorial_djangogirl/tutorial_djangogirl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Category(models.Model):
    categories = (
        ('1', 'crime'),
        ('2', 'buzz'),
        ('3', 'sports')
    )
    title = models.CharField(max_length=50, blank=True, choices=categories)
    

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.ManyToManyField(Category)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

tutorial_djangogirl/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify

class Tag(models.Model):
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text

class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=False)
    slug = models.SlugField(blank=True, editable=False)
    tag = models.ManyToManyField(Tag)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
class Comment(models.Model):
    article = models.ForeignKey('blog.Article', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(null=True)
    created_date = models.DateTimeField(default=timezone.now)

    def save(self):
        self.created_date = timezone.now()
        super(Comment, self).save()
    
    def __str__(self):
        return self.text

blog/forms.py
from django import forms

from .models import Post, Comment, Category

FRUIT_CHOICES= [
    ('orange', 'Oranges'),
    ('cantaloupe', 'Cantaloupes'),
    ('mango', 'Mangoes'),
    ('honeydew', 'Honeydews'),
    ]


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
    favorite_fruit = forms.CharField(label='What is your favorite fruit?', widget=forms.Select(choices=FRUIT_CHOICES))
    

    def clean_your_name(self):
        data = self.cleaned_data['your_name']
        print(data)
        if not data.islower():
           raise forms.ValidationError("Usernames should be in lowercase")
        if 'a' in data:
           raise forms.ValidationError("Usernames should not contain a.")
        return data

class Categoryform(forms.ModelForm):

    categories = (
        ('1', 'red'),
        ('2', 'blue'),
        ('3', 'black')
    )
    category = forms.MultipleChoiceField(required=False, widget=forms.CheckboxSelectMultiple,
    choices=categories)

tutorial_djangogirl/blog/forms.py
from django import forms

from .models import Article, Comment, Tag

class DateInput(forms.DateInput):
    input_type = 'date'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
        }

class ArticleForm(forms.ModelForm):
    choices = Tag.objects.all()
    tagsChoice = []
    for choice in choices:
        tagsChoice.append((choice.id, choice.text))
    

    tags = forms.MultipleChoiceField(
        required=False,
        widget=forms.SelectMultiple(attrs={'class': 'form-control tags'}),
        choices=tagsChoice,
    )

    class Meta:
        model = Article
        fields = ['title', 'text', 'published_date']
        widgets = {
            'title': forms.TextInput(attrs = {'class': 'form-control'}),
            'text': forms.Textarea(attrs = {'class': 'form-control'}),
            'published_date': DateInput(attrs = {'class': 'form-control'}),
        }
    
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')

        if title == 'print':
            self.add_error('title', 'cant use the string print.')
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm, NameForm
from django.shortcuts import redirect

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    category = Category.objects.all(),
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post_detail.html', {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_category(request):
    if request.method == 'POST':
        form = Post_form(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            for k in form.cleaned_data['category']:
                selection = Category.objects.get(pk=k)
                post.category.add(selection)

            return redirect({'form':form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


def post_kosong(request):
    form_kosong = NameForm(request.POST or None)
    if form_kosong.is_valid():          
       return redirect('post_kosong')

    return render(request, 'blog/post_kosong.html', {'form': form_kosong})


def home(request): 
  
    # check if the request is post  
    if request.method =='POST':   
  
        # Pass the form data to the form class 
        details = NameForm(request.POST) 
  
        # In the 'form' class the clean function  
        # is defined, if all the data is correct  
        # as per the clean function, it returns true 
        if details.is_valid():   
  
            # Temporarily make an object to be add some 
            # logic into the data if there is such a need 
            # before writing to the database    
            post = details.save(commit = False) 
  
            # Finally write the changes into database 
            post.save()   
  
            # redirect it to some another page indicating data 
            # was inserted successfully 
            return HttpResponse("data submitted successfully") 
              
        else: 
          
            # Redirect back to the same page if the data 
            # was invalid 
            return render(request, "home.html", {'form':details})   
    else: 
  
        # If the request is a GET request then, 
        # create an empty form object and  
        # render it into the page 
        form = NameForm(None)    
        return render(request, 'home.html', {'form':form}) 


    

tutorial_djangogirl/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticleForm, CommentForm
from .models import Article, Tag, Comment
from django.utils import timezone
from django.db.models import Count


def indexView(request):
    articles = Article.objects.all()
    title = request.GET.get('title')
    tag = request.GET.get('tag')
    if title:
        articles = articles.filter(title__contains=title)
    if tag:
        articles = articles.filter(tag__text=tag)
    context = {
        'articles': articles,  
        'tags': Tag.objects.annotate(num_article = Count('article')),
        'colors': ['danger', 'dark', 'success', 'warning', 'primary']
    }
    return render(request, 'blog/index.html', context)


def article_list(request):
    articles = Article.objects.all()
    title = request.GET.get('title')
    tag = request.GET.get('tag')
    if title:
        articles = articles.filter(title__contains=title)
    if tag:
        articles = articles.filter(tag__text=tag)
    context = {
        'articles': articles,  
        'tags': Tag.objects.annotate(num_article = Count('article')),
        'colors': ['danger', 'dark', 'success', 'warning', 'primary']
    }
    return render(request, 'blog/article_list.html', context)

def article_detail(request, slug):
    article = get_object_or_404(Article, slug=slug)
    comments = article.comments.all()
    form = CommentForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            comment = Comment()
            comment.author = request.user
            comment.article = article
            comment.text = form.cleaned_data['text']
            comment.save()

    context = {
            'article': article,
            'comments': comments,
            'form': form  
        }
    return render(request, 'blog/article_detail.html', context)

def article_new(request):
    form = ArticleForm(request.POST or None)
    tags = Tag.objects.all()

    if request.method == 'POST':
        if form.is_valid():
            article = Article()
            article.author = request.user
            article.title = form.cleaned_data['title']    
            article.text = form.cleaned_data['text']
            article.published_date = form.cleaned_data['published_date']
            tagInput = form.cleaned_data['tags']
            article.save()
            for tag in tagInput:
                article.tag.add(tag)

            return redirect('article_list')
    context = {
        'form': form,
    }
    
    return render(request, 'blog/article_new.html', context) 

def article_edit(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = ArticleForm(request.POST or None, instance=article)
    tags = Tag.objects.all()

    if form.is_valid():
        article = Article()
        article.author = request.user
        article.title = form.cleaned_data['title']    
        article.text = form.cleaned_data['text']
        article.published_date = form.cleaned_data['published_date']
        article.save()

        return redirect('article_list')
    context = {
        'form': form,
    }
    
    return render(request, 'blog/article_edit.html', context) 

def article_delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('article_list')

def article_publish(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.publish()
    return redirect('article_list')
    # if request.method == 'POST':
    #     user = request.user
    #     Article.objects.create(
    #         author = user,
    #         title = request.POST.get('title'),
    #         text = request.POST.get('text'),
    #         published_date = timezone.now(),
    #     )
    #     return redirect('dashboard')
    # else:
    #     return render(request, 'blog/article_new.html', {'form': form}) 

tutorial_djangogirl/blog/templates/blog/article_detail.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="card card-body">
    <div class="card">
        <div class="card-header text-center">
            {{ article.title }}
        </div>
        <div class="card-body">
            {{ article.text }}
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header text-center">
            Comments
        </div>
        <div class="card-body">
            <div class="comments">
                <ul class="list-group list-group-flush">
                    {% for comment in comments %}
                    <li class="list-group-item">
                        <p>{{ comment.author.username }} on {{ comment.created_date }}</p>
                        <p>{{ comment.text }}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% if user.is_authenticated %}
            <form method='POST'>
                {% csrf_token %}
                <label for="id_text">Leave a Comment</label>
                {{ form.text }}
                <input class="btn btn-dark btn-block mt-2" type="submit" value="leave a comment">
            </form>
            {% else %}
            <p class="text-center">Login for leave comment.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

tutorial_djangogirl/blog/templates/blog/article_edit.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="card card-body">
    <div class="card">
        <div class="card-header text-center">
            Edit Article
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Tags</label>
                    {{ form.tags }}
                    <span class="text-danger">{{ form.errors.tags }}</span>
                </div>
                <div class="form-group">
                    <label for="id_title">Title</label>
                    {{ form.title }}
                    <span class="text-danger">{{ form.errors.title }}</span>
                </div>
                <div class="form-group">
                    <label for="id_text">Text</label>
                    {{ form.text }}
                </div>
                <div class="form-group">
                    <label for="id_text">Published Date</label>
                    {{ form.published_date }}
                </div>
                <button class="btn btn-dark" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('.tags').select2({
            tags: true
        });
    });
</script>
{% endblock %}

tutorial_djangogirl/blog/templates/blog/article_list.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="card card-body">
    <div class="card">
        <div class="card-header text-center">
            List Article
            <span class="float-right"><a href="{% url 'article_new' %}" class="btn btn-sm btn-outline-dark">New Article</a></span>
        </div>
        <div class="card-body">
            <div class="filter-area">
                <div class="row justify-content-end">
                    <div class="col-md-4">
                        <form action="#" method="get">
                            <input type="text" class="form-control-inline" name="title" placeholder="search title">
                            <input class="form-control-inline" type="submit" value="Search">
                        </form>
                    </div>
                </div>
                <div class="tag">
                    {% for tag in tags %}
                    <a href="?tag={{ tag.text }}"><span class="badge badge-{{ colors|random }}">{{ tag.text }} {{ tag.num_article }}</span></a>
                    {% endfor %}
                </div>
            </div>
            <table class="table mt-4">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Created Date</th>
                        <th scope="col">Published Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for article in articles %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ article.title }}</td>
                        <td>{{ article.created_date }}</td>
                        <td>
                            {% if article.published_date %}
                            {{ article.published_date }}
                            {% else %}
                            <a href="{% url 'article_publish' pk=article.pk %}" class="btn btn-sm btn-dark">Publish Now</a>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'article_edit' pk=article.pk %}" class="btn btn-sm btn-dark">Edit</a>
                            <a href="{% url 'article_delete' pk=article.pk %}" class="btn btn-sm">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

tutorial_djangogirl/blog/templates/blog/article_new.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="card card-body">
    <div class="card">
        <div class="card-header text-center">
            New Article
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Tags</label>
                    {{ form.tags }}
                    <span class="text-danger">{{ form.errors.tags }}</span>
                </div>
                <div class="form-group">
                    <label for="id_title">Title</label>
                    {{ form.title }}
                    <span class="text-danger">{{ form.errors.title }}</span>
                </div>
                <div class="form-group">
                    <label for="id_text">Text</label>
                    {{ form.text }}
                </div>
                <div class="form-group">
                    <label for="id_text">Published Date</label>
                    {{ form.published_date }}
                </div>
                <button class="btn btn-dark" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('.tags').select2({
            tags: true
        });
    });
</script>
{% endblock %}

tutorial_djangogirl/blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Select2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />

    <title>Django!</title>
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand">Albi</a>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
        {% block body %} {% endblock %}
    </div>

    <!-- jQuery, Popper.js, Bootstrap JS & Select2 JS-->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>

    {% block script %} {% endblock %}
</body>

</html>

tutorial_djangogirl/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="card card-body">
    <div class="card">
        <div class="card-header text-center">
            List Article
            {% if user.is_authenticated %}
            <span class="float-right"><a href="{% url 'article_new' %}" class="btn btn-sm btn-outline-dark">New Article</a></span> 
            {% endif %}
        </div>
        <div class="card-body">
            <div class="filter-area mb-2">
                <div class="row justify-content-end">
                    <div class="col-md-4">
                        <form action="#" method="get">
                            <input type="text" class="form-control-inline" name="title" placeholder="search title">
                            <input class="form-control-inline" type="submit" value="Search">
                        </form>
                    </div>
                </div>
                <div class="tag">
                    {% for tag in tags %}
                    <a href="?tag={{ tag.text }}"><span class="badge badge-{{ colors|random }}">{{ tag.text }} {{ tag.num_article }}</span></a>
                    {% endfor %}
                </div>
            </div>
            
            {% for article in articles %}
            <div class="card card-body">
                <h4>{{ article.title }}</h4>
                <a href="{% url 'article_detail' slug=article.slug %}">See Detail</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}